config/routes.rb
Rails.application.routes.draw do
  get 'answers/result'
  root 'static_pages#index'
  get '/users/new', to: 'users#new'
  get '/other_show', to: 'questions#other'
  get '/help', to: 'static_pages#help'
  resources :users do
    get '/apply_trade', to: 'relations#apply'
    post '/apply_trade', to: 'relations#create'
    get '/questions/new', to: 'questions#new'
    get '/questions/trade', to: 'questions#trade'
    post '/questions/trade', to: 'questions#create'
    get '/questions/:id', to: 'questions#show'
    post '/questions/:id', to: 'questions#enable'
    resources :questions, only: [:new, :index, :show, :create, :destroy]
  end
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :answers, only: [:create]
  post '/apply_trade', to: 'relations#create'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @view_questions = Question.where(created_at: Time.zone.now.all_day, target: true).order("RANDOM()").limit(3)
  end

  def help
  end
end

app/views/static_pages/help.html.slim
.col-md-6.offset-md-3
  h4.text-center.text-muted.my-3 QueAの遊び方
  .card.border-light
    p.text-center.my-5 ヘッダーからユーザー登録ページへ飛びます。
    .text-center= image_tag('new4.jpg', :size => '480x320')
    p.text-center.my-5 ユーザーネーム、パスワード、お住まいの地域、年齢、性別を入力してください。お住まいの地域、年齢、性別は他のユーザーに閲覧される事はありません。
    .text-center= image_tag('new5.png', :size => '480x640')
    p.text-center.my-5 登録が出来たら早速質問を投稿してみましょう。
    .text-center= image_tag('new1.png', :size => '480x320')
    p.text-center.my-5 回答は2から4択を選んでください。質問する内容に困ったら自動質問生成機能を使ってみましょう。
    .text-center= image_tag('new2.jpg', :size => '480x720')
    p.text-center.my-5 質問を投稿するとトレード画面に移動します。ランダムで他ユーザーの質問を表示するので、好きな質問に回答してみてください。いくつでも質問に回答する事が出来ます！
    .text-center= image_tag('new6.png', :size => '480x480')
    p.text-center.my-5 質問に対して回答すると相手のユーザーページに自分の質問を回答してもらう為の通知が届きます。
    .text-center= image_tag('new3.jpg', :size => '480x480')
    p.text-center.my-5 質問の回答結果の詳細はトップページの質問内容をクリックすると見る事が出来ます。タブを切り替えて確認してみてください。
    .text-center= image_tag('new7.png', :size => '480x480')
    p.text-center.my-5 地域、年齢層、性別は有料ユーザーでないと閲覧出来ませんが、現在はユーザー情報更新画面から簡単に有料ユーザーに切り替える事が出来ます。
    .text-center= image_tag('new8.jpg', :size => '480x480')
    .text-center.mt-5= image_tag('new9.png', :size => '480x480')
    p.text-center.my-5 ユーザーネームの上に「Q」アイコンが付きます。
    .text-center.mb-5= image_tag('new10.png', :size => '480x480')

app/views/static_pages/index.html.slim
.col-md-7.offset-md-1.text-center.top
  .mt-5= render 'shared/flash_messages'
  p.border.rounded.bg-gradient-primary.describe.bg-white.border-light QueAは個人で気軽に質問を投稿出来、簡単に回答を集める事が出来るサービスです。相手の質問に答えて、自分の質問にも答えてもらう「質問トレード機能」を備えています。メールアドレス無しでユーザー登録が出来るので気軽に始める事が出来ます。
  - unless logged_in?
    p.mt-5.text_g.text-muted QueAの使い方が分からない方
    = link_to "遊び方", help_path, class: 'btn-hov'
    p.mt-5.text_g.text-muted まだユーザー登録がお済みでない方
    = link_to 'ユーザー登録する', new_user_path, class:'btn-hov'
    p.mt-5.text_g.text-muted ユーザー登録がお済みの方
    = link_to 'ログインする', login_path, class: 'btn-hov'
  - else
    p.mt-5.mb-3.text_g.text-muted #{current_user.name}さん、質問を投稿してみませんか？
    = link_to '質問を投稿する', "/users/#{current_user.id}/questions/new", class: 'btn-hov mt-5'
.col-md-3.visible-lg
  h3.text-center.mt-5.text-muted みんなの最近の質問
  small.text-muted.text-center 質問をクリックすると回答結果を見る事が出来ます。
  .card.mb-5
    .card.open_view.border-light
      - @view_questions.each do |q|
        .card.mb-5
          = link_to other_show_path(ques: q.id),  class: "delete-deco" do
            .card-header.little-hover
              h5.text-dark.text-center= simple_format q.content
              p.text-muted.text-center= q.created_at.strftime('%m月%d日%H時%M分')
          .btn.btn-outline-info.btn-top.my-2= q.num_one
          .btn.btn-outline-info.btn-top.mb-2= q.num_two
          - if q.num_three.present?
            .btn.btn-outline-info.btn-top.mb-2= q.num_three
          - if q.num_four.present?
            .btn.btn-outline-info.btn-top.mb-2= q.num_four