config/routes.rb
Rails.application.routes.draw do
  get 'answers/result'
  root 'static_pages#index'
  get '/users/new', to: 'users#new'
  get '/other_show', to: 'questions#other'
  get '/help', to: 'static_pages#help'
  resources :users do
    get '/apply_trade', to: 'relations#apply'
    post '/apply_trade', to: 'relations#create'
    get '/questions/new', to: 'questions#new'
    get '/questions/trade', to: 'questions#trade'
    post '/questions/trade', to: 'questions#create'
    get '/questions/:id', to: 'questions#show'
    post '/questions/:id', to: 'questions#enable'
    resources :questions, only: [:new, :index, :show, :create, :destroy]
  end
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :answers, only: [:create]
  post '/apply_trade', to: 'relations#create'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  age             :string           not null
#  charged         :boolean          default(FALSE), not null
#  email           :string
#  name            :string           not null
#  password_digest :string
#  prefecture      :integer          not null
#  remember_digest :string
#  sex             :integer          not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  attr_accessor :remember_token
  has_one_attached :image
  attribute :new_image
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  validates :name, presence: true, null: false, uniqueness: true,
            length: { maximu: 15, minimum: 2 }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :prefecture, presence: true
  validates :age, numericality: { only_integer: true, greater_than_or_equal_to: 10, less_than_or_equal_to: 118 }
  validates :sex, presence: true
  enum prefecture: {
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }
  enum sex: {男:0, 女:1}
  validate  :file_validation, if: -> { image.attached? }
  has_secure_password

  before_save do
    self.image = new_image if new_image
  end

  class << self
  # 渡された文字列のハッシュ値を返す
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
               BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # ランダムなトークンを返す
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  # 永続セッションの為にnew_tokenメソッドでランダムなトークンを生成し、データベースに登録する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # 渡されたトークンがremember_digestの値と一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  # ファイルのアップロードサイズのバリデーション
  def file_validation
    # if image.blob.byte_size > 1_000_000
    #   image.purge
    #   file_raise_error('のファイル容量が大きすぎます')
    if !image?
      image.purge
      file_raise_error('は、画像以外はアップロード出来ません')
    end
  end

  def file_raise_error(message)
    image.purge
    errors.add(:avatar, message)
  end

  def validate_image
    return unless image.attached?
    if image.blob.byte_size > 10.megabytes
      image.purge
      errors.add(:image, I18n.t('errors.messages.file_too_large'))
    elsif !image?
      image.purge
      errors.add(:image, I18n.t('errors.messages.file_type_not_image'))
    end
  end

  def image?
    %w[image/jpg image/jpeg image/gif image/png].include?(image.blob.content_type)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :show]
  before_action :correct_user, only: [:edit, :update]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  include UsersHelper


  def show
    # トレード希望者を抽出する
    if has_question?
      @apply_user = Relation.where(answered_user_id: current_user.id)
      # 現在ターゲットになっている質問
      @my_target_question = Question.find_by(user_id: current_user.id, target: true)
      @my_answer_one = Answer.where(answer_result: @my_target_question.num_one, target: true).count
      @my_answer_two = Answer.where(answer_result: @my_target_question.num_two, target: true).count
      @my_answer_three = Answer.where(answer_result: @my_target_question.num_three, target: true).count
      @my_answer_four = Answer.where(answer_result: @my_target_question.num_four, target: true).count
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:notice] = "新規登録しました！次に質問を投稿してみませんか？"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    # if @user.image
    #   begin
    #     show_user_image(@user)
    #   rescue
    #     flash.now[:alert] = "無効な更新です。"
    #     render 'edit'
    #     return
    #   end
    # end
    if @user.update(user_params)
      flash[:notice] = "情報を更新しました。"
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    flash[:alert] = "ユーザーを削除しました。"
    redirect_to root_path
  end

  private

    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation, :new_image, :prefecture, :age, :sex, :charged)
    end

    def set_user
      @user = User.find(params[:id])
    end

    # ログイン済みユーザーかどうか確認
    def logged_in_user
      unless logged_in?
        store_location
        flash[:alert] = "ログインしてください"
        redirect_to login_path
      end
    end

    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def show_user_image(user)
    # unless %w[image/jpg image/jpeg image/gif image/png].include?(user&.image&.blob.content_type)
    #   flash[:alert] = "無効なファイルです。"
    #   redirect_to root_path
    # end
    if user.image.attached?
      begin
        image_tag user.image.variant(resize: "300x300"), class: "img-thumbnail img-r"
      rescue
        user.image.purge
        flash.now[:alert] = "無効なファイルです。"
      end
    else
      image_tag "no_image.png", class: "img-thumbnail"
    end
  end

  def graph_judge_user
    if (@my_answer_one + @my_answer_two + @my_answer_three + @my_answer_four) == 0
      "まだ回答がありません。"
    elsif @my_question.blank?
      pie_chart [[@my_target_question.num_one, @my_answer_one], [@my_target_question.num_two, @my_answer_two]], donut: true
    elsif @my_question.num_three.present?
      pie_chart [[@my_target_question.num_one, @my_answer_one], [@my_target_question.num_two, @my_answer_two], [@my_target_question.num_three, @my_answer_three]], donut: true
    else
      pie_chart [[@my_target_question.num_one, @my_answer_one], [@my_target_question.num_two, @my_answer_two], [@my_target_question.num_three, @my_answer_three], [@my_target_question.num_four, @my_answer_four]], donut: true
    end
  end

  def has_question?
    if Question.find_by(user_id: current_user.id, target: true)
      return true
    else
      return false
    end
  end
end

app/views/users/edit.html.slim
= render 'shared/user_profile', user: @user
.col-md-6.offset-md-1
  = render 'shared/flash_messages'
  = render 'shared/error_messages', obj: @user
  .card.my-5.text-center.border-light
    = form_with model: @user, local: true do |f|
      .form-group
        = f.label :name
        = f.text_field :name, placeholder: "#{@user.name}", class: "form-control edit-form"
        small.text-muted.form-text 最低2文字で入力してください。
      .form-group.mt-2
        = f.label :prefecture
        |(必須)
        = f.select :prefecture, User.prefectures.keys, {prompt: "選択してください"}, class: "form-control edit-form"
      .form-group.mt-2
        = f.label :age
        |(半角数字のみで入力してください)
        |(必須)
        = f.text_field :age, class: "form-control age_field"
      .form-group.mt-2
        = f.label :charged
        = f.check_box 'charged', {}, checked_value="true", unchecked_value="false"
        small.text-muted.form-text チェックボックスにチェックを入れると有料ユーザーになります。
      .form_group.mt-2
        = f.label :new_image
        = f.file_field :new_image, class: "form-control"
      .text-center.my-3= f.submit "この情報で更新する", class: "btn btn-outline-info", data: { disable_with: "送信中・・・" }
      .text-center.mt-5= link_to "アカウントを削除する", user_path(@user), method: :delete, class: "btn btn-outline-danger", data: { confirm: "本当に削除しちゃいますか？" }
      small.text-danger.form-text.mb-5 一度削除したユーザーは二度と復元出来ません。ご注意下さい。

app/views/users/new.html.slim
.container-fluid
  .row
    .signup.col-md-5.col-md-offset-4.text-center
      h4.my-4.text-muted.text_g ユーザー登録
      p.text-muted.text-center 全ての登録情報は他ユーザーから閲覧される事はありません。
      = form_with model: @user, local: true do |f|
        = render 'shared/error_messages', obj: @user
        .card.mb-5.signup-body.border-light
          .form-group.mt-2
            = f.label :name
            |(必須)
            = f.text_field :name, class: "form-control"
            small.text-muted.form-text 最低2文字で入力してください。
            small.text-muted.form-text ※登録したユーザーネームはログイン時に使用します。
          .form-group.mt-2
            = f.label :prefecture
            |(必須)
            = f.select :prefecture, User.prefectures.keys, {prompt: "選択してください"}, class: "form-control"
          .form-group.mt-2
            = f.label :age
            |(数字のみで入力してください)
            |(必須)
            = f.text_field :age, class: "form-control age_field"
            small.text-muted.form-text 入力例「27」
          .form-group.mt-2
            = f.label :sex
            |(必須)
            = f.select :sex, [["男", "男"], ["女", "女"]], {prompt: "選択してください"}, class: "form-control"
          .form-group.mt-2
            = f.label :password
            |(必須)
            = f.password_field :password, class: "form-control"
            small.text-muted.form-text 最低6文字で入力してください。
          .form-group.mt-2
            = f.label :password_confirmation
            |(必須)
            = f.password_field :password_confirmation, class: "form-control"
            small.text-muted.form-text 上で入力したパスワードをもう一度入力してください。
          =f.submit '新規登録',  class: 'btn-gradient-3d-simple mt-5 mb-5', data: { disable_with: "送信中・・・" }

app/views/users/regist.html.slim
= render 'shared/user_profile'

app/views/users/show.html.slim
= render 'shared/user_profile', user: @user
.col-md-9
  .mt-5 = render 'shared/flash_messages'
  .card.mb-5.show-area.border-light
    - if has_question?
      - if @apply_user.present?
        = link_to '質問交換希望相手が居ます！', user_apply_trade_path(current_user), class: "btn-round cp_btn mt-5 little-hover bg-white"
      .text-center
        h5.my-3 現在トレード中の質問
        = link_to "/users/#{current_user.id}/questions/#{@my_target_question.id}", class: "delete-deco" do
          .my_question.text-muted= simple_format @my_target_question.content
        small.text-muted ↑から質問の詳細を確認出来ます。
        .my-4= graph_judgement(@my_target_question, @my_answer_one, @my_answer_two, @my_answer_three, @my_answer_four)
    -else
      p.text-center まだ何も投稿した質問がありません。質問を投稿してみませんか？
    .mt-5= link_to '新しい質問を投稿する', new_user_question_path(current_user), class: "cp_btn_blue text-center little-hover bg-white"
    small.text-muted.text-center.mb-5 ※質問を投稿するとトレードする質問が変更になります。
    -if has_question?
      = link_to '質問をトレードする', user_questions_trade_path(current_user), class: "cp_btn_blue text-center little-hover bg-white"
      small.text-muted.text-center.mb-5 ※他の人の質問を探す事が出来ます。