config/routes.rb
Rails.application.routes.draw do
  get 'answers/result'
  root 'static_pages#index'
  get '/users/new', to: 'users#new'
  get '/other_show', to: 'questions#other'
  get '/help', to: 'static_pages#help'
  resources :users do
    get '/apply_trade', to: 'relations#apply'
    post '/apply_trade', to: 'relations#create'
    get '/questions/new', to: 'questions#new'
    get '/questions/trade', to: 'questions#trade'
    post '/questions/trade', to: 'questions#create'
    get '/questions/:id', to: 'questions#show'
    post '/questions/:id', to: 'questions#enable'
    resources :questions, only: [:new, :index, :show, :create, :destroy]
  end
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :answers, only: [:create]
  post '/apply_trade', to: 'relations#create'
end

app/views/shared/_error_messages.html.slim
- if obj.errors.any?
  #error_explanation
    ul
      - obj.errors.full_messages.each do |msg|
        li.new-errors.mt-2 = msg

app/views/shared/_flash_messages.html.slim
- if flash.notice
  .alert.alert-success[role="alert"]
    = flash.notice
    button.close[type="button" data-dismiss="alert" aria-label="Close"]
      span[aria-hidden="true"]
        | ×
- if flash.alert
  .alert.alert-danger[role="alert"]
    = flash.alert
    button.close[type="button" data-dismiss="alert" aria-label="Close"]
      span[aria-hidden="true"]
        | ×

app/views/shared/_user_profile.html.slim
.col-md-3
  .card.mt-5.text-center.little-hover.border-light
    .pt-5= show_user_image user
    - if user.charged == true
      i.fab.fa-quora.fa-2x.my-orange#charge_icon[data-content="有料ユーザーです"]
    h5.my-3.text_g.text-muted= current_user.name
    -if has_question?
      = link_to "あなたの投稿した質問", user_questions_path(current_user), class: "word_btn to_index"
    = link_to "あなたの情報を更新する", edit_user_path(current_user), class: "word_btn to_index"