config/routes.rb
Rails.application.routes.draw do
  get 'answers/result'
  root 'static_pages#index'
  get '/users/new', to: 'users#new'
  get '/other_show', to: 'questions#other'
  get '/help', to: 'static_pages#help'
  resources :users do
    get '/apply_trade', to: 'relations#apply'
    post '/apply_trade', to: 'relations#create'
    get '/questions/new', to: 'questions#new'
    get '/questions/trade', to: 'questions#trade'
    post '/questions/trade', to: 'questions#create'
    get '/questions/:id', to: 'questions#show'
    post '/questions/:id', to: 'questions#enable'
    resources :questions, only: [:new, :index, :show, :create, :destroy]
  end
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :answers, only: [:create]
  post '/apply_trade', to: 'relations#create'
end

app/views/layouts/_header.html.slim
header
  .navbar.navbar-dark.bg-white.fixed-top
    = link_to 'QueA', root_path, class: 'logo navbar-brand text-muted text_logo'
    ul.nav.navbar-nav.flex-row.justify-content-end
      li.nav-item= link_to "遊び方", help_path, class: 'nav-link text-muted text_g'
      - if logged_in?
        li.nav-item= link_to "#{current_user.name}", current_user, class: 'nav-link text-muted text_g'
        li.nav-item= link_to "質問投稿", new_user_question_path(current_user), class: 'nav-link text-muted text_g'
        li.nav-item= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link text-muted text_g'
      - else
        li.nav-item= link_to 'ログイン', login_path, class: 'nav-link text-muted text_g'
        li.nav-item= link_to '新規登録', new_user_path, class: 'nav-link text-muted text_g'

app/views/layouts/_header_phone.html.slim
header
  .navbar.navbar-dark.bg-white.fixed-top
    = link_to 'QueA', root_path, class: 'logo navbar-brand text-muted text_logo'
    #nav_toggle
      div
        span
        span
        span
    nav
      ul
        li.nav-item= link_to "遊び方", help_path, class: 'nav-link text-muted text_g'
        - if logged_in?
          li.nav-item= link_to "#{current_user.name}", current_user, class: 'nav-link text-muted text_g'
          li.nav-item= link_to "質問投稿", new_user_question_path(current_user), class: 'nav-link text-muted text_g'
          li.nav-item= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link text-muted text_g'
        - else
          li.nav-item= link_to 'ログイン', login_path, class: 'nav-link text-muted text_g'
          li.nav-item= link_to '新規登録', new_user_path, class: 'nav-link text-muted text_g'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | QueA
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    meta[name="viewport" content="width=device-width,initial-scale=1.0"]
  body
    = render 'layouts/header_phone'
    .container-fluid
      .row
        = yield